[package]
name = "engine"
edition = "2024"
version.workspace = true

[dependencies]
common = { path = "../common" }
sstable = { path = "../sstable" }
storage = { path = "../storage" }
transaction = { path = "../transaction" }
tokio.workspace = true
tracing.workspace = true
wal = { path = "../wal" }

[dev-dependencies]
tempfile.workspace = true
storage = { path = "../storage", features = ["testing"] }
