[package]
name = "collection"
edition = "2024"
version.workspace = true

[dependencies]
common = { path = "../common" }
dashmap.workspace = true
memtable = { path = "../memtable" }
sstable = { path = "../sstable" }
tokio.workspace = true
wal = { path = "../wal" }

[dev-dependencies]
tempfile.workspace = true
