[package]
name = "transaction"
edition = "2024"
version.workspace = true

[dependencies]
common = { path = "../common" }
memtable = { path = "../memtable" }
storage = { path = "../storage" }
tokio.workspace = true

[dev-dependencies]
tempfile.workspace = true
storage = { path = "../storage", features = ["testing"] }
